### ISSUE TITLE
devide match number to row content size might be better inflecting trend

### ISSUE THREAD

**Issue by timqian** [timqian/hacker-job-trends#12]

**Comment by devndive** [comment]
Looking into this issue I discovered that right now only the first page of the "Who is hiring story" is processed. Also if you try to scrape more pages you get blocked by HN ;)

To solve this i started using the API of HN. You can now use either relative or absolute numbers.
You can try it `node src/api/index.js react --relative` in my repo
Default is to use absolute numbers.

My clone: https://github.com/devndive/hacker-job-trends
If you like it, let me know if I should create a pull request / clean up or do things differently.

**Comment by timqian** [comment]
@devndive Thanks for your work @devndive I did not notice the "who is hiring story" has more than one page. Using API of HN is definitely a better idea.

Creating PR is very welcomed.

The only issue I see is it seems adding to many files to github, maybe we can ignore the row data.

**Comment by devndive** [comment]
> The only issue I see is it seems adding to many files to github, maybe we can ignore the row data.
I totally agree with you. Did not think about that before. I removed the raw api data and check if we have a processed file before requesting data from the api again.

**Comment by devndive** [comment]
I think issue can be closed now
