### ISSUE TITLE
Scripts to generate charts (ascii and html)

### ISSUE THREAD

**Issue by devndive** [timqian/hacker-job-trends#17]
When analysing a new post with jobs one has to update all the charts in the README.md manually. When adding more queries this becomes more work.

Also when people want to compare the stats for certain queries, it is almost impossible to do this in an easy way.

To address these challenges I created scripts and templates to automate this, #16

**Comment by timqian** [comment]
This is awesome

**Comment by devndive** [comment]
This is what it looks like right now.

<img width="1221" alt="hacker-job-trends" src="https://user-images.githubusercontent.com/10836210/54136603-67a2b400-441c-11e9-950c-91cd2b2188e0.png">

**Comment by timqian** [comment]
hi @devndive  the pr is merged and the charts are deployed, http://timqian.com/hacker-job-trends/

I am always wondering if we can extend this lib, and analyze the whole HN, I am sure there are many interesting and valuable informations hidden in HN posts/comments. A good UI to dig out value out of HN will be great.

like collecting big companies' initial show HNs. what books HNs suggest reading for certain areas. etc.

## existing products:
- https://hn.algolia.com/ I use this search tool occationally, to find HNs' suggestions about certain area

**Comment by timqian** [comment]
what's your thoughts about it?

**Comment by devndive** [comment]
Hi,

I am not quite sure if I can follow our idea. Can we move that discussion to a new issue.
For me to understand an example would help. From there we can start exploring the API and see what we can actually do.

**Comment by timqian** [comment]
@devndive Yeah, that is not related to this issue

**Comment by timqian** [comment]
I will create a new issue for my thoughts
